name = "gestor-nomina"
main = "worker.js"
compatibility_date = "2024-11-01"

# Configuraci√≥n de D1 Database
[[d1_databases]]
binding = "DB"
database_name = "asistencia-db"
database_id = "aa36639b-e17a-4f18-8f8a-c00d664944a5"

# Variables de entorno (opcional)
[vars]
ENVIRONMENT = "production"
BROWSERLESS_API_KEY = ""

[[services]]
binding = "ASISTENCIA"
service = "asistencia-backend"

[triggers]
crons = ["0 */6 * * *"]
